"use client"
import React from 'react'
import "@/app/globals.css"
import { useSession } from 'next-auth/react'
import { useRouter } from 'next/router'

const page = () => {
  const { data: session } = useSession()
  if (session) {
    
    console.log("There is session")
    console.log("session", session.user?.email)
  }
  return (
    <div className='text-black min-h-screen text-center'>
       <h1 className='font-medium text-xl'>
       Hello This is about page Lorem ipsum dolor sit amet consectetur, adipisicing elit. Et reiciendis nam ullam a corporis nisi cumque commodi fuga. Nulla, magni consequatur, laboriosam labore dolorum sed, iste ipsa explicabo fugit repellendus inventore id.
       Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloribus, molestias deleniti dicta a mollitia illum, error dolores maxime optio magnam vel, veniam sequi voluptate! Ex tempore vitae saepe unde nam rerum rem nesciunt velit voluptatem neque nobis dolores dolorem asperiores earum voluptatibus numquam eveniet, maiores iusto dicta possimus? Necessitatibus quo incidunt at, facere fugit, ea veniam error aliquid quos sed possimus voluptate? Earum eligendi ex, voluptatem fugiat illo nam distinctio consectetur dolore, dignissimos fugit inventore, soluta reiciendis minima et nostrum quidem atque! Soluta quis nulla sequi culpa, necessitatibus laudantium laboriosam voluptatibus quam tenetur, quisquam id aut. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deserunt similique asperiores saepe mollitia enim voluptas nulla autem quia error officiis! Atque dolores accusantium quibusdam similique aut, provident ratione mollitia, architecto consequuntur cumque minus, distinctio harum. Aliquam expedita similique voluptatum id in ratione adipisci nobis reprehenderit delectus ad earum voluptatem aut nostrum quaerat, sint perferendis assumenda optio consequatur beatae ipsam molestias! Placeat similique tempore eaque sed beatae quis dolor provident eius ut itaque obcaecati blanditiis assumenda vel voluptatem magni vero aut soluta, inventore cumque neque harum voluptatum ex at. Veritatis odit dolores, doloremque sed exercitationem accusantium? Sint nihil necessitatibus temporibus quam iure accusamus ex hic. Eos molestias, delectus labore reprehenderit fuga ratione. Cumque praesentium illum impedit iusto quam doloremque consequuntur odit itaque dolorem magnam aperiam, quos excepturi placeat reiciendis!
        </h1> 
       <h1 className='font-medium text-xl'>
       Hello This is about page Lorem ipsum dolor sit amet consectetur, adipisicing elit. Et reiciendis nam ullam a corporis nisi cumque commodi fuga. Nulla, magni consequatur, laboriosam labore dolorum sed, iste ipsa explicabo fugit repellendus inventore id.
       Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloribus, molestias deleniti dicta a mollitia illum, error dolores maxime optio magnam vel, veniam sequi voluptate! Ex tempore vitae saepe unde nam rerum rem nesciunt velit voluptatem neque nobis dolores dolorem asperiores earum voluptatibus numquam eveniet, maiores iusto dicta possimus? Necessitatibus quo incidunt at, facere fugit, ea veniam error aliquid quos sed possimus voluptate? Earum eligendi ex, voluptatem fugiat illo nam distinctio consectetur dolore, dignissimos fugit inventore, soluta reiciendis minima et nostrum quidem atque! Soluta quis nulla sequi culpa, necessitatibus laudantium laboriosam voluptatibus quam tenetur, quisquam id aut. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deserunt similique asperiores saepe mollitia enim voluptas nulla autem quia error officiis! Atque dolores accusantium quibusdam similique aut, provident ratione mollitia, architecto consequuntur cumque minus, distinctio harum. Aliquam expedita similique voluptatum id in ratione adipisci nobis reprehenderit delectus ad earum voluptatem aut nostrum quaerat, sint perferendis assumenda optio consequatur beatae ipsam molestias! Placeat similique tempore eaque sed beatae quis dolor provident eius ut itaque obcaecati blanditiis assumenda vel voluptatem magni vero aut soluta, inventore cumque neque harum voluptatum ex at. Veritatis odit dolores, doloremque sed exercitationem accusantium? Sint nihil necessitatibus temporibus quam iure accusamus ex hic. Eos molestias, delectus labore reprehenderit fuga ratione. Cumque praesentium illum impedit iusto quam doloremque consequuntur odit itaque dolorem magnam aperiam, quos excepturi placeat reiciendis!
        </h1> 
       <h1 className='font-medium text-xl'>
       Hello This is about page Lorem ipsum dolor sit amet consectetur, adipisicing elit. Et reiciendis nam ullam a corporis nisi cumque commodi fuga. Nulla, magni consequatur, laboriosam labore dolorum sed, iste ipsa explicabo fugit repellendus inventore id.
       Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloribus, molestias deleniti dicta a mollitia illum, error dolores maxime optio magnam vel, veniam sequi voluptate! Ex tempore vitae saepe unde nam rerum rem nesciunt velit voluptatem neque nobis dolores dolorem asperiores earum voluptatibus numquam eveniet, maiores iusto dicta possimus? Necessitatibus quo incidunt at, facere fugit, ea veniam error aliquid quos sed possimus voluptate? Earum eligendi ex, voluptatem fugiat illo nam distinctio consectetur dolore, dignissimos fugit inventore, soluta reiciendis minima et nostrum quidem atque! Soluta quis nulla sequi culpa, necessitatibus laudantium laboriosam voluptatibus quam tenetur, quisquam id aut. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deserunt similique asperiores saepe mollitia enim voluptas nulla autem quia error officiis! Atque dolores accusantium quibusdam similique aut, provident ratione mollitia, architecto consequuntur cumque minus, distinctio harum. Aliquam expedita similique voluptatum id in ratione adipisci nobis reprehenderit delectus ad earum voluptatem aut nostrum quaerat, sint perferendis assumenda optio consequatur beatae ipsam molestias! Placeat similique tempore eaque sed beatae quis dolor provident eius ut itaque obcaecati blanditiis assumenda vel voluptatem magni vero aut soluta, inventore cumque neque harum voluptatum ex at. Veritatis odit dolores, doloremque sed exercitationem accusantium? Sint nihil necessitatibus temporibus quam iure accusamus ex hic. Eos molestias, delectus labore reprehenderit fuga ratione. Cumque praesentium illum impedit iusto quam doloremque consequuntur odit itaque dolorem magnam aperiam, quos excepturi placeat reiciendis!
        </h1> 
       <h1 className='font-medium text-xl'>
       Hello This is about page Lorem ipsum dolor sit amet consectetur, adipisicing elit. Et reiciendis nam ullam a corporis nisi cumque commodi fuga. Nulla, magni consequatur, laboriosam labore dolorum sed, iste ipsa explicabo fugit repellendus inventore id.
       Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloribus, molestias deleniti dicta a mollitia illum, error dolores maxime optio magnam vel, veniam sequi voluptate! Ex tempore vitae saepe unde nam rerum rem nesciunt velit voluptatem neque nobis dolores dolorem asperiores earum voluptatibus numquam eveniet, maiores iusto dicta possimus? Necessitatibus quo incidunt at, facere fugit, ea veniam error aliquid quos sed possimus voluptate? Earum eligendi ex, voluptatem fugiat illo nam distinctio consectetur dolore, dignissimos fugit inventore, soluta reiciendis minima et nostrum quidem atque! Soluta quis nulla sequi culpa, necessitatibus laudantium laboriosam voluptatibus quam tenetur, quisquam id aut. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deserunt similique asperiores saepe mollitia enim voluptas nulla autem quia error officiis! Atque dolores accusantium quibusdam similique aut, provident ratione mollitia, architecto consequuntur cumque minus, distinctio harum. Aliquam expedita similique voluptatum id in ratione adipisci nobis reprehenderit delectus ad earum voluptatem aut nostrum quaerat, sint perferendis assumenda optio consequatur beatae ipsam molestias! Placeat similique tempore eaque sed beatae quis dolor provident eius ut itaque obcaecati blanditiis assumenda vel voluptatem magni vero aut soluta, inventore cumque neque harum voluptatum ex at. Veritatis odit dolores, doloremque sed exercitationem accusantium? Sint nihil necessitatibus temporibus quam iure accusamus ex hic. Eos molestias, delectus labore reprehenderit fuga ratione. Cumque praesentium illum impedit iusto quam doloremque consequuntur odit itaque dolorem magnam aperiam, quos excepturi placeat reiciendis!
        </h1> 
    </div>
  )
}

export default page